### PR TITLE
Week calendar 📅

### PR DESCRIPTION
**Pull request by Azmah-Bad**
#29 adde week view for the calendar

### CODE REVIEW

**Review by titouan-joseph — CHANGES_REQUESTED** [review]
Forgot lib prettytable in requirements.txt

**Comment by Azmah-Bad** [comment]
https://media1.tenor.com/images/5928958c42329cf6e101dda2ad295393/tenor.gif?itemid=7848720

**Comment by Azmah-Bad** [comment]
image

**Review by titouan-joseph — APPROVED** [review]
image

**Comment by Azmah-Bad** [comment]
iu

**Pull request merged**
